SELECT ID, MOVIE , DESCRIPTION ,RATING FROM

(SELECT ID, MOVIE,description, CASE
WHEN ID%2=0 THEN 'EVEN'
ELSE 'ODD'
END AS T,RATING FROM CINEMA
WHERE description!='boring') AS TA
WHERE TA.T='ODD'
ORDER BY RATING DESC